sudo: false
language: node_js
node_js:
    - "6.2"
before_install:
    - "npm install -g npm"
    - "npm install -g grunt-cli"
    - "npm install yellowlabtools"
install:
    - "npm install"
before_script:
    - grunt yellowlabtools:twitterLocal
    - grunt yellowlabtools:twitterDistant